name: CI

on: [push, pull_request]

jobs:
  job_build:
    name: Compilation
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-builder:latest

    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Build
        run: |
          cd workdir/app-near/ && make && mv bin/ NEAR-bin/

      - name: Upload NEAR app binary
        uses: actions/upload-artifact@v2
        with:
          name: NEAR-app
          path: workdir/app-near/NEAR-bin

  job_test:
    name: Tests
    needs: job_build
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/ledgerhq/speculos:latest
      ports:
        - 1234:1234
        - 9999:9999
        - 40000:40000
        - 41000:41000
        - 42000:42000
        - 43000:43000
      options: --entrypoint /bin/bash

    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Download NEAR app binary
        uses: actions/download-artifact@v2
        with:
          name: NEAR-app
          path: workdir/app-near/NEAR-bin

      - name: Install tests dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y qemu-user-static
          pip install --extra-index-url https://test.pypi.org/simple/ -r workdir/app-near/tests/requirements.txt

      - name: Run tests
        run: |
          cd workdir/app-near/ && SPECULOS=/speculos/speculos.py pytest tests --sdk 2.0 --headless
